openapi: "3.0.3"
info:
  description: link-list-api
  title: LinkListApi
  version: ${project.version}
tags:
  - name: link
  - name: meilisearch
  - name: group
paths:
  /api/v1/group:
    post:
      tags:
        - group
      operationId: createGroup
      description: create a group
      requestBody:
        description: CreateGroupRequest
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateGroupRequest"
        required: true
      responses:
        "201":
          description: GroupResponse
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GroupDto"
    get:
      tags:
        - group
      operationId: getGroups
      description: Get groups
      responses:
        "200":
          description: GroupResponse
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GroupDto"
  /api/v1/group/{groupId}:
    patch:
      tags:
        - group
      operationId: joinGroup
      description: join a group
      parameters:
        - $ref: "#/components/parameters/GroupId"
      responses:
        "200":
          description: GroupResponse
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GroupDto"
  /api/v1/link:
    post:
      tags:
        - link
      operationId: createLinkItem
      description: create a link-item
      requestBody:
        description: CreateLinkItemRequest
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateLinkItemRequest"
        required: true
      responses:
        "201":
          description: LinkResponse
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LinkItemDto"
    get:
      tags:
        - link
      operationId: getAllLinks
      description: get all link-items
      responses:
        "200":
          description: LinkItemResponse
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/LinkItemDto"
  /api/v1/link/{linkId}:
    delete:
      tags:
        - link
      operationId: deleteLinkItem
      description: delete link-item
      parameters:
        - $ref: "#/components/parameters/LinkId"
      responses:
        "200":
          description: LinkItemResponse
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LinkItemDto"
    put:
      tags:
        - link
      operationId: updateLinkItem
      description: update link-item
      parameters:
        - $ref: "#/components/parameters/LinkId"
      responses:
        "200":
          description: LinkItemResponse
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LinkItemDto"
  /api/v1/search-link:
    post:
      tags:
        - meilisearch
      operationId: searchForLinks
      description: search for link-items
      requestBody:
        description: MeilisearchSearchRequest
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MeilisearchSearchRequest"
        required: true
      responses:
        "200":
          description: LinkItemResponse
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MeilisearchLinkSearchResponse"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    LinkId:
      in: path
      name: linkId
      required: true
      schema:
        type: integer
        format: int64
      description: The link ID
    GroupId:
      in: path
      name: groupId
      required: true
      schema:
        type: integer
        format: int64
      description: The group ID
  schemas:
    CreateGroupRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        users:
          type: array
          items:
            type: string
    GroupDto:
      type: object
      allOf:
        - $ref: "#/components/schemas/CreateGroupRequest"
      properties:
        id:
          type: integer
          format: int64
    CreateLinkItemRequest:
      type: object
      required:
        - url
        - title
        - description
      properties:
        url:
          type: string
        title:
          type: string
        description:
          type: string
    LinkItemDto:
      type: object
      required:
        - id
        - url
        - title
        - description
      allOf:
        - $ref: "#/components/schemas/CreateLinkItemRequest"
      properties:
        id:
          type: integer
          format: int64
    AuthenticationResponse:
      type: object
      required:
        - token
      properties:
        token:
          type: string
    MeilisearchLinkSearchResponse:
      type: object
      required:
        - limit
        - page
        - totalPages
      properties:
        hits:
          type: array
          items:
            $ref: "#/components/schemas/LinkItemDto"
        limit:
          type: integer
        page:
          type: integer
        totalPages:
          type: integer
    MeilisearchSearchRequest:
      type: object
      required:
        - q
        - page
        - hitsPerPage
      properties:
        q:
          type: string
        page:
          type: integer
        hitsPerPage:
          type: integer
security:
  - bearerAuth: [ ]